
on: [push]

jobs:
    check_style_job:
        runs-on: ubuntu-latest
        name: A job to check java code style
        steps:
        - name: Checkout code step
          uses: actions/checkout@v2
        - name: CheckStyle action step
          id: checkstyle
          uses: bshewan/checkstyle-action@16f49d17615fb5c4be1c385fe98634286017c521
        - name: Completion step
          run: echo "Completed checking the style!"
