
on: [push]

jobs:
    check_style_job:
        runs-on: ubuntu-latest
        name: A job to check java code style
        steps:
        - name: CheckStyle action step
          id: checkstyle
          uses: bshewan/checkstyle-action@437db79f368f72a17972e2778baa6d8893405856
        - name: Completion step
          run: echo "Completed checking the style!"
